[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

remappings = [
    "@openzeppelin/contracts/=dependencies/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=dependencies/openzeppelin-contracts-upgradeable/contracts/",
    "@balancer-labs/=node_modules/@balancer-labs",
    "@uniswap/=node_modules/@uniswap"
]
fs_permissions = [{ access = "read", path = "./out"}]
